### ISSUE TITLE
Profile preview has disappeared

### ISSUE THREAD

**Issue by Eudaldca** [jacobbearden/overcast-plus#10]
![](http://i.imgur.com/W7vsLYL.png)

**Comment by jacobbearden** [comment]
@Eudaldca Can you open up dev tools and send a screenshot of any errors/warnings?

It's working fine for me:
![image](https://cloud.githubusercontent.com/assets/5340692/16670817/6f783aa8-4459-11e6-8e5c-1436a31725d3.png)

**Comment by Eudaldca** [comment]
It now works for me, I'll update this if I get this issue again.
