### ISSUE TITLE
In preview, not all headings are displayed correctly

### ISSUE THREAD

**Issue by MrTheSharpie** [jacobbearden/overcast-plus#2]
If you write a heading like this, it will be displayed as normal text in the preview.

```
TITLE
-----
```

However, if you write it like this, it will be displayed correctly.

`## TITLE ##`

**Comment by MrTheSharpie** [comment]
¯\_(ツ)_/¯

**Comment by jacobbearden** [comment]
Since the network is shutting down I'm ceasing development on this, sorry!

**Comment by jacobbearden** [comment]
Cancel that :smile:

**Comment by jacobbearden** [comment]
Should be fixed in 3d16cdd3502a1b693ef27270764ad5394bfdb281
