### ISSUE TITLE
When you switch to a different page it flashes between normal and dark theme.

### ISSUE THREAD

**Issue by LArrowHead** [jacobbearden/overcast-plus#9]
I can't get a screenshot of this, but basically if you go to a different page (like the home page to forums) with your dark theme enabled it will flash from dark to original to dark again really quickly.

**Comment by jacobbearden** [comment]
Not fixable, Chrome defaults to a white background, and the flash you see is before the plugin can even kick in and set the theme. Sorry :cry:

**Comment by LArrowHead** [comment]
Alright thanks anyways
